- name: Create a db on MSSQL using DSC
  hosts: all
  gather_facts: no
  become: no
  vars:
    login_user: sa
    login_password: "{{ mssql_password }}"
    instance_name: "{{ ansible_hostname }}"
    sql_query: CREATE DATABASE ['{{ db_name }}']
  tasks:
    - ansible.builtin.debug:
        msg: "creating {{ db_name }}"

    - include_role:
        name: sql_run_sql_script_dsc